# Generated by Django 5.1.2 on 2024-11-23 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to='user/', verbose_name='Photo Perfil'),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, help_text='Alias único para la cuenta', max_length=100, null=True, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('Alquileres', 'Alquileres'), ('Aportes de capital', 'Aportes de capital'), ('Bienes registrables habitualistas', 'Bienes registrables habitualistas'), ('Bienes registrables no habitualistas', 'Bienes registrables no habitualistas'), ('Cuota', 'Cuota'), ('Expensas', 'Expensas'), ('Factura', 'Factura'), ('Haberes', 'Haberes'), ('Honorarios', 'Honorarios'), ('Inmobiliaria habitualista', 'Inmobiliaria habitualista'), ('Inmobiliaria', 'Inmobiliaria'), ('Préstamos', 'Préstamos'), ('Seguros', 'Seguros'), ('Suscripción a obligaciones negociables', 'Suscripción a obligaciones negociables'), ('Varios', 'Varios')], default='Varios', help_text='Motivo de la transferencia', max_length=50)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='usuarios.cuenta')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_realizadas', to='usuarios.cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
