# Generated by Django 5.1.2 on 2024-11-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_photo_cuenta_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(null=True, upload_to='perfiles/', verbose_name='Photo Perfil'),
        ),
    ]
